export const Questions = [
  {
    prompt: 'Louis Tomlinson co-wrote which One Direction song that topped the charts in multiple countries?',
    optionA: 'Story of My Life',
    optionB: 'What Makes You Beautiful',
    optionC: 'Drag Me Down',
    optionD: 'Little Things',
    answer: 'A',
  },
  {
    prompt: "Louis' football charity match, Soccer Aid, raises funds for which organization?",
    optionA: 'UNICEF',
    optionB: 'Red Cross',
    optionC: 'Amnesty International',
    optionD: 'World Wildlife Fund',
    answer: 'A',
  },
  {
    prompt: 'Louis has a production company named Triple Strings Ltd. What year was this company officially registered?',
    optionA: '2014',
    optionB: '2015',
    optionC: '2016',
    optionD: '2017',
    answer: 'B',
  },
  {
    prompt: 'Louis has a half-sister from his father`s side. What is her name?',
    optionA: 'Phoebe',
    optionB: 'Georgia',
    optionC: 'Ashley',
    optionD: 'Briana',
    answer: 'B',
  },
  {
    prompt: 'Louis co-wrote a song for One Direction album Midnight Memories which features a folk-inspired sound and showcases his vocal range. What is the title of this song?',
    optionA: 'Little Black Dress',
    optionB: 'Diana',
    optionC: 'Dont Forget Where You Belong',
    optionD: 'Strong',
    answer: 'C',
  },
  {
    prompt: 'Louis` debut solo single, Just Hold On, was performed for the first time on live television during which program?',
    optionA: 'Saturday Night Live',
    optionB: 'The Ellen DeGeneres Show',
    optionC: 'The Voice UK',
    optionD: 'The X Factor UK',
    answer: 'D',
  },
  {
    prompt: 'Before One Direction, Louis Tomlinson was an actor in a school production of which popular musical?',
    optionA: 'Les Misérables',
    optionB: 'Grease',
    optionC: 'The Phantom of the Opera',
    optionD: 'Cats',
    answer: 'B',
  },
  {
    prompt: 'Louis` debut solo album, Walls, was released in which year?',
    optionA: '2018',
    optionB: '2019',
    optionC: '2020',
    optionD: '2021',
    answer: 'C',
  },
  {
    prompt: 'Louis Tomlinson participated in the "Celebrity Gogglebox" special for charity. Which charity did the proceeds of this special benefit?',
    optionA: 'Comic Relief',
    optionB: 'British Heart Foundation',
    optionC: 'Children in Need',
    optionD: 'Stand Up To Cancer',
    answer: 'D',
  },
  {
    prompt: 'Louis co-wrote the song "Love You Goodbye" for "Made in the A.M." Which other member of the band co-wrote this song with him?',
    optionA: 'None, Louis Tomlinson solely wrote this song.',
    optionB: 'Niall Horan',
    optionC: 'Harry Styles',
    optionD: 'Liam Payne',
    answer: 'A',
  },
]